name = "StaticLists"
uuid = "d1891b89-3aa8-469e-a5ac-90bba77ac8f3"
authors = ["Zachary P. Christensen <zchristensen7@gmail.com> and contributors"]
version = "0.3.1"

[deps]
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
Static = "0.6, 0.7"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
